### ISSUE TITLE
Localize UI component

### ISSUE THREAD

**Issue by lorenzulrich** [visol/Visol.Neos.LinkClass#2]
The two labels "Link Class" (label of select) and "Choose link class" (placeholder for select) should be localized. Furthermore, the labels should be renamed to emphasize that the styling of the link is changed (class doesn't necessary mean anything to a non-technical CMS editor).

## English

* Link style
* Choose link style...

## German

* Link-Stil
* Link-Stil wählen...

**Comment by dimaip** [comment]
Fixed in https://github.com/visol/Visol.Neos.LinkClass/commit/af032131252b7dfb71372c2006319895f74d9eb1
