### ISSUE TITLE
Is this package compatible with Neos UI v5.0?

### ISSUE THREAD

**Issue by breadlesscode** [visol/Visol.Neos.LinkClass#3]
Hello,

first, thanks for this awesome plugin. :)

But is this package compatible with Neos UI v5.0? I want to integrate it in my current Neos-Project..

**Comment by lorenzulrich** [comment]
I wouldn't see why not. Could you test and maybe create a PR with currently supported UI versions? I don't have 5.x running at the moment.

**Comment by breadlesscode** [comment]
Okay, will test it next Week :) Thanks for your feedback

**Comment by breadlesscode** [comment]
Tested with Neos 5.0 and Neos UI 5.0, works great :)
