### ISSUE TITLE
Neos 7.x compatibility

### ISSUE THREAD

**Issue by paavo** [visol/Visol.Neos.LinkClass#9]
Currently – as per `composer.json` – this package is not compatible with Neos 7. 
Therefore we need to check / fix / update it.

**Comment by lorenzulrich** [comment]
That's right, we did not test this yet. If you are currently working with Neos 7, please test it and provide a PR so we can do a new release. Based on the changes for Neos 7, I think no modifications will be necessary.

**Comment by paavo** [comment]
Looks like no modification was necessary:
Created PR https://github.com/visol/Visol.Neos.LinkClass/pull/10
